# Source: questdb/templates/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: questdb-headless
  labels:
    helm.sh/chart: questdb-0.20.2
    app.kubernetes.io/name: questdb
    app.kubernetes.io/instance: questdb
    app.kubernetes.io/version: "6.4"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgresql
      port: 8812
      targetPort: postgresql
  selector:
    app.kubernetes.io/name: questdb
    app.kubernetes.io/instance: questdb